### PR TITLE
Fix the malformed OWL restrictions.

### PR DESCRIPTION
**Pull request by rpgoldman**
Add Jupyter notebook with the code for finding and fixing ill-formed
owl:Restriction definitions.

Also add revised versions of the paml.ttl and uml.ttl files.

Finally, add pairs of .nt files that can be diffed to see what
happened in the repair.

I propose we could add my code for finding bad restrictions to the git
repo as a before-commit hook.  To do so, we would need to pull the
code out of the notebook.

### CODE REVIEW

**Comment by rpgoldman** [comment]
As an aside, when I looked at the PAML spec, it seemed to have places where we set the maximum cardinality and the minimum cardinality to 1 using `owl:maxCardinality` and `owl:minCardinality`.

But I think in that case we could just use `owl:cardinality` and set it to 1.

**Comment by rpgoldman** [comment]
# RDF repair versus source repair

With all due respect, I reported the ill-formed restrictions ages ago, and no one seemed to have any energy to fix them.  I tried to fix a few (maybe in the SBOL?), but as an operation on text, it is *very* laborious, and as far as I can tell, *every* restriction definition was busted.  Auto-repair seemed like the best option under the circumstances.

I do agree that a text-to-text transform would be better, but it would involve something that reliable found the restrictions, found the `onProperty` they contain, and then multiplied that across the type, value, and cardinality constraints.  I don’t have the time or energy to do that, and as far as I can tell, no one else does, either.

At the expense of repeating myself: this is one of many reasons I don’t think using RDF + OWL as our representation is a good choice. A standard isn’t a good standard if it’s this difficult to get something that’s even *syntactically* well-formed. This also demonstrates that an *RDF* editor is not sufficient to get well-formed OWL.  If we are going to have OWL constructs in our source code, we should have an editor that understands it.

# N-triples

As for the n-triples files, that’s what rdflib gave me when I asked it to serialize to a file with an “.nt” extension.  Perhaps something additional needs to be done to get *sorted* n-triples?  Is sorted n-triples different from standard .nt ? I recalled your saying you used rdflib to get the sorted ntriples so that’s what I tried. Please let me know how to produce them, and I will do so.

I wasn’t intending for the n-triples files to stay in the repository: just be there temporarily since we don’t have a diff solution for the Turtle files.  But they give us only a *semantic* diff, not a *syntactic* diff for anything that is edited as code.

# Moving the code out of the notebook

I can easily move the code out: where do you want it? It’s not really part of the module, so perhaps I should put it in a `scripts` directory?  I’ll do that when you let me know what you would like to see happen.

**Comment by jakebeal** [comment]
Here is the code that pySBOL uses to get sorted ntriples format:
```
        if file_format == SORTED_NTRIPLES:
            # have RDFlib give us the ntriples as a string
            nt_text = graph.serialize(format=NTRIPLES)
            # split it into lines
            lines = nt_text.splitlines(keepends=True)
            # sort those lines
            lines.sort()
            # write out the lines
            # RDFlib gives us bytes, so open file in binary mode
            result = self.join_lines(lines)
```

I'm happy to make the corrections, I just need something that tells me which ones are broken so that I know which to fix. This is what happened when @bbartley tried to fix earlier as well -- the checker that he found didn't think that there were problems.

Can I suggest please turn this script into a test that will report the broken elements as errors?  It can report all or it can report just the first it finds, I just need something to give me a breadcrumb in service of incremental progress. When you've got that in and failing, you can pass it over to me and I'll take the branch from there.

**Comment by rpgoldman** [comment]
@jakebeal 
> Here is the code that pySBOL uses to get sorted ntriples format:
> 
...

I made this into the `owl_rdf_utils.to_sorted_ntriples` module.  But this does not seem to do that well with the blank nodes for restrictions.  Have you been doing something else to make the blank nodes diff-able?

**Comment by rpgoldman** [comment]
@jakebeal IIUC, your `paml.ttl` has some definitions in it that rdflib thinks are superfluous:

```
###  http://www.w3.org/2002/07/owl#maxCardinality
owl:maxCardinality rdf:type owl:AnnotationProperty .
owl:minCardinality rdf:type owl:AnnotationProperty .
```

This seems to contradict [the actual OWL definitions](http://www.w3.org/2002/07/owl), e.g.:

```
owl:maxCardinality a rdf:Property ;
     rdfs:label "maxCardinality" ;
     rdfs:comment "The property that determines the cardinality of a maximum cardinality restriction." ;
     rdfs:domain owl:Restriction ;
     rdfs:isDefinedBy <http://www.w3.org/2002/07/owl#> ;
     rdfs:range xsd:nonNegativeInteger .
```

This specifically is a violation because one cannot specify range constraints on annotation properties.  I believe it should be benign to remove these?

**Comment by rpgoldman** [comment]
@jakebeal OK, here's how to run the new script to check your code:

```
python -m owl_rdf_utils.restrictions  check paml.ttl
```

For the current version, this produces:

```
Found bad restrictions in graph
ub1bL158C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:allValuesFrom om:Measure
	owl:maxCardinality <1>
	owl:onProperty paml:amount
	owl:minCardinality <1>

ub1bL361C13 a http://www.w3.org/2002/07/owl#Restriction
	owl:maxCardinality <1>
	owl:onProperty paml:contents
	owl:allValuesFrom xsd:string
	owl:minCardinality <1>
	ub1bL361C13 rdfs:comment N-dimensional array of URI for specification or nulls

ub1bL79C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:onProperty paml:completedNormally
	owl:minCardinality <1>
	owl:maxCardinality <1>
	owl:allValuesFrom xsd:boolean

ub1bL441C29 a http://www.w3.org/2002/07/owl#Restriction
	owl:minCardinality <1>
	owl:maxCardinality <1>
	owl:onProperty paml:fromSamples
	owl:allValuesFrom paml:SampleCollection

ub1bL128C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:onProperty paml:parameter
	owl:minCardinality <1>
	owl:maxCardinality <1>
	owl:allValuesFrom uml:Parameter

ub1bL231C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:allValuesFrom uml:ActivityEdge
	owl:minCardinality <0>
	owl:maxCardinality <1>
	owl:onProperty paml:edge

ub1bL435C29 a http://www.w3.org/2002/07/owl#Restriction
	owl:minCardinality <1>
	owl:maxCardinality <1>
	owl:allValuesFrom xsd:string
	owl:onProperty paml:sampleDataValues

ub1bL355C13 a http://www.w3.org/2002/07/owl#Restriction
	owl:onProperty paml:containerType
	owl:minCardinality <1>
	owl:maxCardinality <1>
	owl:allValuesFrom xsd:anyURI
	ub1bL355C13 rdfs:comment Type of container used for storing the samples. The size and dimension may not match that of the array: it is up to execution to lay out the array in one or more containers

ub1bL297C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:minCardinality <1>
	owl:maxCardinality <1>
	owl:onProperty paml:call
	owl:allValuesFrom paml:BehaviorExecution

ub1bL156C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:allValuesFrom sbol:TopLevel
	owl:minCardinality <1>
	owl:maxCardinality <1>
	owl:onProperty paml:specification

ub1bL393C13 a http://www.w3.org/2002/07/owl#Restriction
	owl:maxCardinality <1>
	owl:allValuesFrom paml:SampleCollection
	owl:onProperty paml:source
	owl:minCardinality <1>

ub1bL233C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:maxCardinality <1>
	owl:allValuesFrom sbol:Identified
	owl:onProperty paml:edgeValue
	owl:minCardinality <1>

ub1bL235C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:allValuesFrom paml:ActivityNodeExecution
	owl:onProperty paml:tokenSource
	owl:minCardinality <1>
	owl:maxCardinality <1>

ub1bL187C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:maxCardinality <1>
	owl:allValuesFrom paml:Protocol
	owl:onProperty paml:protocol
	owl:minCardinality <1>

ub1bL398C13 a http://www.w3.org/2002/07/owl#Restriction
	owl:onProperty paml:mask
	owl:maxCardinality <1>
	owl:allValuesFrom xsd:string
	owl:minCardinality <1>

ub1bL130C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:onProperty paml:parameterValue
	owl:allValuesFrom uml:LiteralSpecification
	owl:minCardinality <1>
	owl:maxCardinality <1>

ub1bL271C5 a http://www.w3.org/2002/07/owl#Restriction
	owl:maxCardinality <1>
	owl:onProperty paml:node
	owl:allValuesFrom uml:ActivityNode
	owl:minCardinality <1>
```

Note also that this script will set the exit status to 1 if there are bad restrictions, else 0. So this can be used in any Unix-style pipeline we would like.

**Comment by rpgoldman** [comment]
P.S. I converted this to draft, because I don't want to merge it until I clean up the history and add some more docs.

**Comment by jakebeal** [comment]
> I made this into the `owl_rdf_utils.to_sorted_ntriples` module. But this does not seem to do that well with the blank nodes for restrictions. Have you been doing something else to make the blank nodes diff-able?

We don't normally end up with blank nodes in SBOL serializations, so I haven't encountered this issue.

> @jakebeal IIUC, your paml.ttl has some definitions in it that rdflib thinks are superfluous:

If losing them isn't affecting the ability of sbol_factory to work and thus the PAML tests to run, then I guess they aren't needed.

> ```
> ub1bL158C5 a http://www.w3.org/2002/07/owl#Restriction
>	owl:allValuesFrom om:Measure
>	owl:maxCardinality <1>
>	owl:onProperty paml:amount
>	owl:minCardinality <1>

Am I understanding correctly that this means that it needs to be broken into four individual restriction statements? If so, then I think I'm good to go with this.

**Comment by rpgoldman** [comment]
Shouldn’t this have been merged by now?

**Comment by jakebeal** [comment]
@bbartley : as you've been doing the upgrades from SBOL_factory, please take this on too.

**Comment by rpgoldman** [comment]
@jakebeal @bbartley What's the status of this?  Right now we have OWL code that is still syntactically ill-formed. I would really like to see this repaired.

I can sort of understand that the auto-fix was unsatisfactory because it didn't diff well, but now we seem to be wedged. What gets us unstuck?

**Comment by bbartley** [comment]
@rpgoldman I am currently working down through the issues in this thread and will try to close this outstanding PR today

**Comment by rpgoldman** [comment]
That's great to hear. Please let me know if there's anything I can do with my script to make this go more smoothly.

**Comment by bbartley** [comment]
@rpgoldman what is the status of https://github.com/rpgoldman/paml/blob/fix-restrictions/notebooks/paml-revised.nt?  Was this revised file generated by your auto-repair script?  Some of the restrictions are still failing validation with `AssertionError: No components to restriction Nb6aa0a3e39e8453484d9690fd3091124`

**Comment by rpgoldman** [comment]
I'm trying to recall the status -- I'm afraid that me_{now} doesn't know all that me_{then} once did.

I tried to look at your error message, and couldn't find a restriction `Nb6aa0a3e39e8453484d9690fd3091124` in that source file.  What did you do to get that error, and I will retry.

**Comment by rpgoldman** [comment]
BTW, when I try to parse that `.nt` file, `rdflib` complains that it doesn't like the first line:

```
<?xml version="1.0" encoding="UTF-8"?>
```

Any idea why it wouldn't?

**Comment by bbartley** [comment]
It's because the file is actually xml and it is inferring that it is n-triples.

**Comment by rpgoldman** [comment]
@bbartley OK, I think I see what I did wrong making those files: I assumed `rdflib`'s serialize method would choose the format based on the file extension, and it didn't.  I needed to explicitly supply `format='nt'`.

@jakebeal I'm not sure I understand the role of sorted n triples here. Yes, it's diffable, but it's not effectively readable or writeable for humans, so how do we use it in the development process? Should we be using it only as an ephemeral format to be used for comparison, and use turtle the rest of the time?

Also, if we are going to use sorted n-triples for diffing, shouldn't we be doing something about the blank nodes?  Should we do a first pass of assigning them meaningful names?  Seems like somehow these should be made to line up with the source lines in the Turtle file, and I'm not sure how to do that.

**Comment by jakebeal** [comment]
@rpgoldman For OWL, I think doing it in turtle is fine.  

Sorted N-triples works a lot better with SBOL, where we're generating material and it all is intended to have predictable and stable names --- there it's an advantage, where turtle is a disadvantage because autogenerated turtle is not stable. Here, however, where material is hand-generated and the anonymous names are intended to be unstable I am seeing that turtle is a better format.

**Comment by rpgoldman** [comment]
> @rpgoldman For OWL, I think doing it in turtle is fine.
> 
> Sorted N-triples works a lot better with SBOL, where we're generating material and it all is intended to have predictable and stable names --- there it's an advantage, where turtle is a disadvantage because autogenerated turtle is not stable. Here, however, where material is hand-generated and the anonymous names are intended to be unstable I am seeing that turtle is a better format.

Maybe this would work: https://www.w3.org/2001/sw/wiki/How_to_diff_RDF

apparently also rdflib supports skolemization, so we could name all the blank nodes if that would help.

One thing that would be really helpful would be if we could somehow track graph nodes and edges to lines of code in a turtle file, but I don't know if that is possible.  Looking at RDFLib, it seems not

**Comment by rpgoldman** [comment]
OK, there is good news and bad news:  the good news is that all the restrictions tests seem to be fixed now.  The bad news is that there are a bunch of other tests failing.  Do I assume correctly that these are still holdovers from our problems with rdflib?

**Review by bbartley — APPROVED** [review]

**Comment by bbartley** [comment]
All Restrictions are cleaned up and tests are passing.  Tests now invoke @rpgoldman's standalone, commandline script for checking Restrictions.  The jupyter notebooks have been removed.   

@jakebeal have your requested changes been adequately addressed?

**Review by jakebeal — APPROVED** [review]

**Pull request merged**
