### PR TITLE
Make paml:Primitive disjointWith uml:Activity.

### PR DESCRIPTION
**Pull request by rpgoldman**
According to the paper, Activity is intended to capture only *complex*
behaviors, so should be a class that is disjoint with activity.

### CODE REVIEW

**Comment by jakebeal** [comment]
Note that you'll want to check to make certain that sbol_factory isn't confused by this. I don't think it should be a problem, as sbol_factory ought to ignore this and make things disjoint in Python by default. We haven't ever had a test case like this before, however.

**Comment by rpgoldman** [comment]
Looks like SBOL factory does not like this, but ...  Here's the error message, from the check, which I don't really understand.

```
E   ImportError: cannot import name 'parser' from 'rdflib_jsonld' (/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/rdflib_jsonld/__init__.py)
```

@bbartley -- any idea?  See https://github.com/Bioprotocols/paml/runs/4291173573?check_suite_focus=true

**Comment by rpgoldman** [comment]
OK: there's a confound.  The `main` branch of PAML is broken, as far as I can tell. See https://github.com/Bioprotocols/paml/runs/4291378318?check_suite_focus=true

I *suspect* that this is because of RDFLIB updates, but I can't say for sure.

But I believe all merging for this repo should go on hold until our test suite is fixed.

**Comment by bbartley** [comment]
This branch has gone stale and bringing it up to date was causing beaucoup CI issues. Since the change was simple, I created a fresh PR here: #105

**Pull request closed without merging**
