### PR TITLE
Add new GitHub action to test for bad OWL Restriction's

### PR DESCRIPTION
**Pull request by rpgoldman**
These seem to keep creeping back in, or else they were never corrected.  Trying to add a check to our GitHub Actions CI.

### CODE REVIEW

**Comment by rpgoldman** [comment]
OK, this is ready to go. Should be squash-merged.  Note that it is on top of #122, so should be merged *after* that. 

Note also that the tests fail on this because they *should* fail: we have two ill-formed OWL files in the repo.

**Comment by rpgoldman** [comment]
Looks like there's still an issue with the script.

**Comment by rpgoldman** [comment]
@bbartley Please have a look at this: it's ready to go now.

**Review by danbryce — APPROVED** [review]

**Comment by rpgoldman** [comment]
Manually merged this: wanted to squash merge, and have more control over the commit message than GitHub would give me. Closing.

**Pull request closed without merging**
